### PR TITLE
Fix the cache being fetched twice

### LINKED ISSUE #239: Cache fetched twice?
I was just restarting trRouting while watching the logs, and it seems the cache is fetched twice. A first time, after the "Sorting connections..." message, it goes back to "Initializing modes..." and logs are repeated until the server is ready.

I'm starting trRouting from Transition, on the v2c branch.

### PR DESCRIPTION
**Pull request by tahini**
Fixes #239

The `loadAllData` function should be called only once in the TransitData constructor.

### CODE REVIEW

**Review by kaligrafy — APPROVED** [review]

**Comment by tahini** [comment]
@greenscientist  any idea what's the problem with macos builds? You temporarily fixed something recently. Is it related? though this one seems to be about pkg-config...

**Comment by greenscientist** [comment]
About the macos build, maybe the pkg-config package was there by default in the image and not there anymore. I imagine we should try to add it manually in our build

File: src/transit_data.cpp [hunk 1]
```diff
@@ -20,9 +20,8 @@ namespace TrRouting {
   TransitData::TransitData(DataFetcher& fetcher) :
     dataFetcher(fetcher)
   {
-    
-    loadAllData();
-    if(loadAllData() != DataStatus::READY ) {
+
+    if (loadAllData() != DataStatus::READY) {
```
Comment (greenscientist) [inline src/transit_data.cpp]: Instead, can you put the result of loadAllData in a variable and check that in the if.

**Review by greenscientist — CHANGES_REQUESTED** [review]

**Review by greenscientist — APPROVED** [review]
