### PR TITLE
Fix assert in optimise_journey

### LINKED ISSUE #207: Assertion failed for some queries
error: Assertion failed: (trip.reverseConnectionsIdx.size() > 1 + sequenceEndIdx), function optimizeJourney, file optimize_journey.cpp, line 177.

### PR DESCRIPTION
**Pull request by greenscientist**
Comparison should be >= instead of just >

Closes #207

### CODE REVIEW

File: connection_scan_algorithm/src/optimize_journey.cpp [hunk 1]
```diff
@@ -171,7 +171,7 @@ namespace TrRouting
         int sequenceStartIdx = std::get<journeyStepIndexes::FINAL_ENTER_CONNECTION>(journey[fromJourneyStepIdx]).value()->getSequenceInTrip() - 1;
         int sequenceEndIdx   = std::get<journeyStepIndexes::FINAL_EXIT_CONNECTION >(journey[fromJourneyStepIdx]).value()->getSequenceInTrip() - 1;
 
-        assert(trip.reverseConnections.size() > 1 + sequenceEndIdx); // make sure sequenceIdx will be valid
+        assert(trip.reverseConnections.size() >= 1 + sequenceEndIdx); // make sure sequenceIdx will be valid
```
Comment (tahini) [inline connection_scan_algorithm/src/optimize_journey.cpp:175]: Is that the index starting with 1? Worth commenting as it would be unintuitive to anyone...

**Review by tahini — CHANGES_REQUESTED** [review]

File: connection_scan_algorithm/src/optimize_journey.cpp (hunk 1 above)
Comment (greenscientist) [reply connection_scan_algorithm/src/optimize_journey.cpp:175]: Frankly, I'm not 100% sure, but I think I've seen this while looking at other part of the code.

**Comment by greenscientist** [comment]
@tahini Let me know if you prefer with this comment.

**Review by tahini — APPROVED** [review]
